name: marimo_env_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>=3.10
  - pip:
      - docutils>=0.21
      - duckdb>=1.2
      - marimo>=0.11
      - markdown>=3.7
      - numpy>=2.2
      - pandas>=2.2
      - parso>=0.8
      - plotly>=6.0
      - polars>=1.25
      - pyarrow>=17.0.0
      - pyocclient>=0.6
      - seaborn>=0.13
